language: node_js
node_js: "8"

branches:
  only: 
    - master

before_install:
  - npm i npm@^6 -g

install:
  - npm install
  - npm i @types/node

before_script:
  - npm install -g ionic cordova
  - npm install -g @angular/cli

script:
  - ionic cordova build browser - prod
  - ng build --prod --aot