language: node_js
node_js:
 - '10.16.0'

sudo: true
dist: trusty 

branches:
 only:
 - master

before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 
script:
  - ng test --watch false -cc
  - npm run e2e
  - ng build -bh "https://antoniotavares20.github.io/monitora-mobile/"
  - ionic cordova build browser --prod


deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: dist