language: node_js
stage: deploy

node_js:
 - '10.16.0'

sudo: true
dist: trusty 

branches:
 only:
 - master

cache:

  directories:
    - node_modules

before_script:
- npm install -g ionic cordova
- npm install firebase-tools -g
- ionic cordova plugin add cordova-plugin-firebase
- npm install @ionic-native/firebase
- cd functions && npm install


script:
-  ionic build --prod -- --base-href='https://antoniotavares20.github.io/monitora-mobile/'
- firebase deploy --only hosting,functions --token $FIREBASE_TOKEN


deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www